# Generated by Django 3.2.11 on 2022-02-11 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 15, 26, 11, 330112, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
